[package]
name = "sharedmem_comm"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "sharedmem_comm"
path = "src/lib.rs"

[dependencies]
densearray = "*"
sharedmem = "*"
